### ISSUE TITLE
Locked pressure plate chat spam

### ISSUE THREAD

**Issue by srnyx** [commandgeek/geeksmp#68]
### Expected behavior

It should only send 1 message each time the pressure plate is stepped on.

### Actual behavior

It will send a message either every tick or second (can't tell) that you are on a locked pressure plate.

### Steps to reproduce

Stand on a locked pressure plate that you didn't lock.
![java_D9BrfOjorf](https://user-images.githubusercontent.com/25808801/153099976-3f06bd7f-f277-4cdb-8b4f-30924b45216a.gif)

### Minecraft version and OS

1.18.1, Windows 10

### Checks

- [X] I am using modifications (mods, resourcepacks, etc...). (check if yes)
- [X] I asked in the Discord to see whether this issue is in fact a bug that needs to be fixed.

**Comment by DWAA1660** [comment]
this is fixed @srnyx im pretty sure

**Comment by srnyx** [comment]
> this is fixed @srnyx im pretty sure

When was it fixed?

**Comment by ReeceTD** [comment]
This is not fixed.
Tested today [as of the 11th of March 2022, 3:07AM GMT]

Evidence:
![image](https://user-images.githubusercontent.com/98226198/157794592-2f5d73ab-a906-493a-a86f-8c9ebd6e10da.png)
